<?php
	$_ICON['type_1']='推荐';
	$_ICON['type_2']='视频';
	$_ICON['type_3']='音乐';
	$_ICON['type_4']='读书';
	$_ICON['type_5']='体育';
	$_ICON['type_6']='社交';
	$_ICON['type_7']='游戏';
	$_ICON['type_8']='新闻';
	$_ICON['type_9']='工具';
